--- # https://www.ansiblepilot.com/articles/create-kubernetes-k8s-or-openshift-ocp-namespace-project-ansible-module-k8s/
- name: nmsp k8s
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    project_name: "app-project"
  tasks:
    - name: create {{ project_name }} namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ project_name }}"
        state: present
